export const GET_COMPANY_DATA_INIT = 'App/GET_COMPANY_DATA_INIT';
export const GET_COMPANY_DATA_SUCCESS = 'App/GET_COMPANY_DATA_SUCCESS';
export const GET_COMPANY_DATA_ERROR = 'App/GET_COMPANY_DATA_ERROR';
export const GET_EMPLOYEES_DATA_INIT = 'App/GET_EMPLOYEES_DATA_INIT';
export const GET_EMPLOYEES_DATA_SUCCESS = 'App/GET_EMPLOYEES_DATA_SUCCESS';
export const GET_EMPLOYEES_DATA_ERROR = 'App/GET_EMPLOYEES_DATA_ERROR';
export const SET_SELECTED_EMPLOYEE = 'App/SET_SELECTED_EMPLOYEE';
export const RESET_SELECTED_EMPLOYEE = 'App/RESET_SELECTED_EMPLOYEE';
